'use client';

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { GeneratePersonalizedRoadmapOutput } from '@/ai/flows/generate-personalized-roadmap';
import type { FormValues } from '@/lib/types';

const parseList = (text: string | undefined): string[] => {
  if (!text) return [];
  return text.split('\n').map(s => s.replace(/^- /, '').trim()).filter(Boolean);
};

export const generatePdf = (data: GeneratePersonalizedRoadmapOutput, studentData: FormValues) => {
    const doc = new jsPDF();

    // Set document properties
    doc.setProperties({
        title: `Vidyatej Career Roadmap for ${studentData.aimingCareer}`,
        subject: 'Your Personalized AI-Generated Career Roadmap',
        author: 'Vidyatej',
    });

    // Add Header
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(24);
    doc.text('Vidyatej – Igniting Bright Futures', doc.internal.pageSize.getWidth() / 2, 20, { align: 'center' });
    
    doc.setFontSize(16);
    doc.setFont('helvetica', 'normal');
    doc.text(`Your Personalized Roadmap to Become a ${studentData.aimingCareer}`, doc.internal.pageSize.getWidth() / 2, 30, { align: 'center' });

    let y = 45;

    // Add a section with a title and content
    const addSection = (title: string, content: string | string[]) => {
        if (doc.internal.pageSize.getHeight() - y < 40) {
            doc.addPage();
            y = 20;
        }
        
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(14);
        doc.text(title, 14, y);
        y += 8;

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(11);

        if (Array.isArray(content)) {
            autoTable(doc, {
                startY: y,
                body: content.map(item => [item]),
                theme: 'grid',
                styles: {
                    cellPadding: 2,
                    fontSize: 10,
                },
                headStyles: {
                    fillColor: [255, 255, 255], // White
                    textColor: [0, 0, 0],
                },
                didDrawPage: (data) => {
                    y = data.cursor?.y ?? y;
                }
            });
            y = (doc as any).lastAutoTable.finalY + 10;
        } else {
            const splitText = doc.splitTextToSize(content, 180);
            doc.text(splitText, 14, y);
            y += (splitText.length * 5) + 10;
        }
    };
    
    // Student's Profile Section
    addSection("Student Profile", [
        `Stream: ${studentData.stream}`,
        `Specialization: ${studentData.specialization}`,
        `Year of Study: ${studentData.yearOfStudy}`,
        `Aiming Career: ${studentData.aimingCareer}`,
        `Target Salary: ${studentData.salaryRange}`,
    ]);


    // Motivational Nudge
    if (data.motivationalNudge) {
        y += 5;
        doc.setFont('helvetica', 'italic');
        doc.setTextColor(100);
        const splitNudge = doc.splitTextToSize(`"${data.motivationalNudge}"`, 180);
        doc.text(splitNudge, doc.internal.pageSize.getWidth() / 2, y, { align: 'center'});
        y += (splitNudge.length * 5) + 10;
        doc.setTextColor(0);
        doc.setFont('helvetica', 'normal');
    }

    // Roadmap Details
    if (data.skillRoadmap) addSection('Skill Roadmap', parseList(data.skillRoadmap));
    if (data.toolsToMaster) addSection('Tools to Master', parseList(data.toolsToMaster));
    if (data.timeline) addSection('Estimated Timeline', data.timeline);
    if (data.projects) addSection('Project Ideas', parseList(data.projects));
    if (data.resources) addSection('Learning Resources', data.resources);
    if (data.careerGrowth) addSection('Career Growth', data.careerGrowth);
    if (data.resumeInterviewPrep) addSection('Resume & Interview Prep', parseList(data.resumeInterviewPrep));
    if (data.jobMarketInsights) addSection('Job Market Insights', data.jobMarketInsights);

    // Add Footer
    const pageCount = (doc as any).internal.getNumberOfPages();
    doc.setFontSize(8);
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.text(`Page ${i} of ${pageCount} | Generated by Vidyatej`, doc.internal.pageSize.getWidth() / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });
    }

    // Save the PDF
    doc.save(`Vidyatej_Roadmap_${studentData.aimingCareer.replace(/\s+/g, '_')}.pdf`);
};
