import type {NextConfig} from 'next';

const nextConfig: NextConfig = {
  /* config options here */
  typescript: {
    ignoreBuildErrors: true,
  },
  eslint: {
    ignoreDuringBuilds: true,
  },
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'placehold.co',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'images.unsplash.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'picsum.photos',
        port: '',
        pathname: '/**',
      },
    ],
  },
  experimental: {
    // This is the key change to prevent the restart loop.
    // It tells Next.js to ignore files generated by Genkit.
    ignoredBuildTestFiles: ['**/.genkit*'],
  },
  // This allows requests from the Firebase Studio preview URL.
  allowedDevOrigins: ["https://*.cluster-w5vd22whf5gmav2vgkomwtc4go.cloudworkstations.dev"],
};

export default nextConfig;
